Update documentation of wrappedValue force unwrap
JARMourato/Kodable pull request #1
Opened 2021-01-05 22:50 UTC by rogerluan

Hey 👋 

I believe it makes sense to inform users of the lib about this caveat, so I moved it from private to the public instance, and updated the copy a bit. Lemme know your thoughts!

2021-01-05 22:57 UTC, rogerluan commented
On a second thought, I think we'd better throw like this @JARMourato :

```diff
- return _value as! U
+ if value == nil {
+     preconditionFailure(message: "Explain why this cant be done, add the docs here")
+ } else {
+     return _value as! U
+ }
```

Thoughts? 😊

2021-01-05 23:16 UTC, JARMourato commented
[Here](https://github.com/apple/swift/blob/c4c27f63048826678d7a7e6cde4b5797d291cec6/test/decl/var/property_wrappers.swift#L115) is the error it throws if I were to try to make the initializer throw. 

I think it is okay to leave it like this, at least for the use I give to the lib. 

This is the only case where it would crash

```Swift
struct Roger: Kodable {
    @Coding("rogdog") var name: String
}
let r = Roger()
print(r.name) // Crashes when getting the name property because the underlying `_value` is nil
```

I like your suggestion. However, I'd prefer if you use `fatalError` instead of `preconditionFailure`.

2021-01-06 02:49 UTC, rogerluan commented
Seems good to me! 
The crash seems fine (like you said, given the context of the lib), but giving a better user feedback is always important - and `fatalError` does make more sense to me as well 👌

2021-01-06 02:53 UTC, rogerluan commented on Sources/Kodable/KodableTransformable.swift
>          _value as! U
```suggestion
        if _value == nil {
            fatalError(message: "Property with key '\(pending-property-key-here)' couldn't be decoded, and no default value was provided.")
        } else {
            _value as! U
        }
```

Just missing the property key as idk how to get it within this context @JARMourato 🙈

2021-01-13 22:45 UTC, JARMourato approved these changes

2021-01-13 23:00 UTC, JARMourato requested changes

2021-01-13 23:00 UTC, JARMourato commented on Sources/Kodable/KodableTransformable.swift
> +            _value as! U
```suggestion
           return _value as! U
```

2021-01-13 23:00 UTC, JARMourato approved these changes

2021-01-13 23:49 UTC, rogerluan commented on Sources/Kodable/KodableTransformable.swift
> +        }
```suggestion
        if _value == nil {
            fatalError("Trying to access a non optional property that has not been decoded - the property value is nil internally")
        } else {
            return _value as! U
        }
```

2021-01-14 19:38 UTC, merged